version: '3.8'

services:
  backend:
    build: ./backend
    environment:
      POSTGRES_URI: postgresql://postgres:changeme@localhost:5432/postgres
    ports:
      - "8080:8080"
    restart: unless-stopped
